<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="person">
		<email>gentoo@houseofsuns.org</email>
		<name>Markus Walter</name>
	</maintainer>
	<longdescription># python-debianbtsPython-debianbts is a Python library that allows for querying Debian's [BugTracking System](https://bugs.debian.org). Since 2011, python-debianbts is usedby Debian's `reportbug` to query the Bug Tracking System and has currently(2017-11) roughly [190.000 installations](https://qa.debian.org/popcon.php?package=python-debianbts).Online [documentation][] is available on readthedocs.[documentation]: https://python-debianbts.readthedocs.io/en/latest/## Installing```bashpip install python-debianbts```## Quickstart```python&gt;&gt;&gt; import debianbts as bts&gt;&gt;&gt; bts.get_bugs(package='python-debianbts')[803900, 787723, 824111, 639458, 726878, 722226, 789047]&gt;&gt;&gt; bts.get_status([803900, 787723])[&lt;debianbts.debianbts.Bugreport at 0x7f47080d8c10&gt;, &lt;debianbts.debianbts.Bugreport at 0x7f47080d80d0&gt;]&gt;&gt;&gt; for b in bts.get_status([803900, 787723]):...     print(b)...originator: Antonio Terceiro &lt;terceiro@debian.org&gt;date: 2015-06-04 13:09:02subject: reportbug: crashes when querying Debian BTS for reports on wnppmsgid: &lt;20150604130538.GA16742@debian.org&gt;package: python-debianbtstags: ['fixed-upstream', 'patch', 'jessie']done: Trueforwarded: https://github.com/venthur/python-debianbts/pull/5mergedwith: [722226, 726878, 789047]severity: importantowner: found_versions: []fixed_versions: ['python-debianbts/1.13']blocks: []blockedby: []unarchived: Truesummary: affects: []log_modified: 2019-07-08 07:27:36location: archivearchived: Truebug_num: 787723source: python-debianbtspending: donedone_by: Bastian Venthur &lt;venthur@debian.org&gt;originator: Wookey &lt;wookey@debian.org&gt;date: 2015-11-03 01:39:01subject: reportbug errors out with SOAP errormsgid: &lt;20151103013542.11170.31413.reportbug@cheddar.halon.org.uk&gt;package: python-debianbtstags: []done: Falseforwarded: mergedwith: []severity: normalowner: found_versions: []fixed_versions: ['python-debianbts/2.0']blocks: []blockedby: []unarchived: Falsesummary: affects: []log_modified: 2015-11-03 08:36:04location: db-harchived: Falsebug_num: 803900source: python-debianbtspending: pendingdone_by: None```</longdescription>
</pkgmetadata>